FamilyName=Spartan6
VendorName=Xilinx
SynthArchName=spartan6
LogFileName=C:\Users\Public\Documents\Altium\Projects\ESRA_0x0E030206\ProjectOutputs\Default - All Constraints\ESRA_Spartan6.synthlog
OutputFileName=C:\Users\Public\Documents\Altium\Projects\ESRA_0x0E030206\ProjectOutputs\Default - All Constraints\ESRA_Spartan6.edf
BFLFileName=C:\Users\Public\Documents\Altium\Projects\ESRA_0x0E030206\ProjectOutputs\Default - All Constraints\ESRA_Spartan6.bfl
Entity=ESRA_Spartan6
VerilogMode=1
VHDL87=0
InsertIOBuffers=True
SDB_MaxMultipliers=38
InferRam=Auto
RomStyle=Logic
SisOptimizationLevel=High
SDB_ActiveLowAsynPreset=False
SDB_ActiveLowAsynReset=False
SDB_ActiveLowTristate=False
SDB_AlteraAdder=False
SDB_AlteraLpmAddSub=False
SDB_AlteraLpmCompare=False
SDB_AlteraLpmMultiply=False
SDB_AlteraLVDS=False
SDB_EdifBitvecInHex=True
SDB_EnableAsynFlipFlop=True
SDB_EnableLatch=False
SDB_EnableSyncFlipFlop=True
SDB_LatticeCCU2=False
SDB_LatticeCCU2B=False
SDB_LatticeFADD2=False
SDB_LatticeFADD2B=False
SDB_LatticeFSUB2=False
SDB_LatticeFSUB2B=False
SDB_LatticeMult=False
SDB_LatticeMultB=False
SDB_TristateInternalToMux=False
SDB_TristatePushToTop=False
SDB_TristateToMux=False
SDB_XilinxMacroAdder=True
SDB_XilinxMacroMux=True
SDB_XilinxMult=True
SDB_XilinxMuxF56=True
SDB_XilinxMuxF78=False
